# Generated by Django 3.2.2 on 2021-05-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(unique=True, verbose_name='فعال')),
                ('name_template', models.CharField(max_length=255, verbose_name='نام قالب')),
                ('title', models.CharField(max_length=255, verbose_name='نام سایت')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
        ),
    ]
